#!/usr/bin/env python3

from planning_project3.turtlebot import TurtleBot

if __name__ == '__main__':
    turtlebot = TurtleBot()
    actions_list = [(0.1, 0.1)] * 5 + \
                   [(0.2, 0.2)] * 5 + \
                   [(0.3, 0.3)] * 5 + \
                   [(0.2, 0.2)] * 5 + \
                   [(0.1, 0.1)] * 5 + \
                   [(0, 0)] * 5 

    try:
        turtlebot.executeActions(actions_list)
    except rospy.ROSInterruptException:
        pass

